### ISSUE TITLE
Does not compile with Qt Creator 3.3.2?

### ISSUE THREAD

**Issue by dev5000** [OneMoreGres/qtc-gtest#8]
Hello Sergey --

I am having difficulty compiling this plugin for QT Creator 3.3.2 (opensource). In QtcGtestPlugin.cpp, the line that begins with "connect (DocumentModel::model ()," throws the compile error "'model' is not a member of 'Core::DocumentModel'".

I tried commenting out those signal/slot setup lines just to see if I could compile things, but ran into another error in PaneWidget.cpp, on the "#include "ui_PaneWidget.h"" line ("ui_PaneWidget.h: No such file or directory"). It doesn't appear that ui_PaneWidget.h is in this Git project.

I'm running Ubuntu 14.04 LTS. I'd really like to run this on Qt Creator 3.3.2, but it doesn't appear possible to do so at the moment. Any help you could provide would be greatly appreciated. Thanks!

**Comment by OneMoreGres** [comment]
Hello.
At first, you can download latest plugin version from [here](https://sourceforge.net/projects/qtc-gtest/files/bin/).
Honestly, i haven't build it under 3.3.2 because it's binary compatible with 3.3.1. But if you still want to build it by yourself.. :)
Both errors looks like wrong configuration or qtc's source version. Because [model is a member of DocumentModel](https://github.com/qtproject/qt-creator/blob/v3.3.2/src/plugins/coreplugin/editormanager/documentmodel.h) in 3.3.2
and ui_* files are being generated from *.ui files at build time.
Ensure that you use proper version of qt creator, paths in paths.pri, and project settings (haven't tried it without shadow build, however there should be no difference). Then make clean rebuild (with rerunning qmake/removing build dir).

**Comment by dev5000** [comment]
Thank you for your help -- I got it working with the compiled version.
